// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl3kYn5kBV8mLPnj4Y6D58t3AcX0Bf6Rk',
    appId: '1:78164388183:web:e62a4becf69645b98eb612',
    messagingSenderId: '78164388183',
    projectId: 'database-63fca',
    authDomain: 'database-63fca.firebaseapp.com',
    storageBucket: 'database-63fca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJJVAEbTSGjFg8CiI1kkItv1wYQHLukh8',
    appId: '1:78164388183:android:8dfb2bd018c100fb8eb612',
    messagingSenderId: '78164388183',
    projectId: 'database-63fca',
    storageBucket: 'database-63fca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjNpk3t98s0baEa50bUJvpQrK9wCpKFus',
    appId: '1:78164388183:ios:5db20c654043d4e28eb612',
    messagingSenderId: '78164388183',
    projectId: 'database-63fca',
    storageBucket: 'database-63fca.appspot.com',
    iosBundleId: 'com.example.flutterprogra4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjNpk3t98s0baEa50bUJvpQrK9wCpKFus',
    appId: '1:78164388183:ios:0ad6a69f3e9474ac8eb612',
    messagingSenderId: '78164388183',
    projectId: 'database-63fca',
    storageBucket: 'database-63fca.appspot.com',
    iosBundleId: 'com.example.flutterprogra4.RunnerTests',
  );
}
